#import "@preview/lemmify:0.1.8": *
#let (
  theorem,
  lemma,
  corollary,
  remark,
  proposition,
  example,
  proof,
  rules: thm-rules,
) = default-theorems(
  "thm-group",
  lang: "en",
)
#let lemma = lemma.with(numbering: none)
#let theorem = theorem.with(numbering: none)
#show: thm-rules

Thm: Let $f(x_1, ..., x_k)$ be a multi-variate polynomial in $k$ variables and integer coefficients, $m >= 1$. Then $R_m (f(a_1, ..., a_k)) = R_m (f(R_m (a_1), ..., R_m (a_k)))$.

#theorem(name: "Euclidean Theorem")[
  For all integers $a$ and $d eq.not 0$, there are unique $q,r$ such that $a=d q + r$ and $0 <= r < |d|$ ($a$ dividend, $d$ divisor, $q$ quotient)
]
=== Euclidean Algorithm
Start with $m < n$ and replace the pair $(m,n)$ with $R_m (n), m$ until the remainder is zero, at which point the last nonzero number is the gcd of $m,n$.

#figure(image("/media/Euclidean_Algo.png", width: 20em))

/*=== Extended Euclidean Algorithm
Initialize: $"old_r" = a, r=b, "old_s"=1, s=0, "old_t"=0, t=1$
While $r eq.not 0:$
- $q= floor.l "old_r"/r floor.r$
- $("old_r", r) = (r, "old_r" - q r)$
- $("old_s, s" = (s, "old_s" - q s))$
- $("old_t", t) = (t, "old_t" - q t)$
Then: $gcd(a, b) = "old_r", x = "old_s", y = "old_t"$*/

*Example (RSA)*
With $p=61, q=53$:
- $n = p q = 61*53 = 3233$
- $phi(n) = 60*52 = 3120$
- Choose a coprime $e$, e.g., $e=17$.
- Now compute $d equiv e^(-1) (mod 3120)$, i.e., $17d equiv 1 (mod 3120)$
- $17x + 3120y = 1$
- Euclidean: $3120 = 17*183 + 9 --> 17 = 9*1 + 8 --> 9 = 8*1 + 1 --> 8 = 1*8+0$ so $gcd(17, 3120)=1$
Back substitution:
- From the previous step: $1 = 9-8*1$
- From the one before: $8=17-9*1$, so:
- $1 = 9 - (17-9) = 9-17+9 = 2*9 - 17$
- ...
- $1 = (-367)17 + 2*3120 --> x=-367, y=2 --> d=-367 equiv 2653 (mod 3120)$


*GCD Simplification* $gcd(m, n-q m)=gcd(m, n)$, thus $gcd(m, R_m (n))=gcd(m, n)$

*Ideals* $(a,b)= {u a + v b | u,v in ZZ}$. Every ideal in $ZZ$ can be generated by a single integer.\
Hence: $gcd(a, b)=u a+v b$

== Expressing $lcm, gcd$
Per the unique factorization theorem, any ${a,b} subset.eq ZZ$ can be written as\ $ a=product_i p_i^(e_i), b=product_i p_i^(f_i) $

$ gcd(a, b)=product_i p_i^(min(e_i, f_i)), lcm(a, b) = product_i p_i^(max(e_i, f_i)) $
And because $min(x, y)+max(x, y)=x+y$, we get $gcd(a, b) dot lcm(a, b) = a b$.

== Modulo
*See Relations for definition of modular congruence.*

$a eq b <==> a equiv b (mod m)$

If $a equiv b (mod m), c equiv d (mod m)$:

$a+c equiv (b+d) (mod m) "and" a c equiv b d (mod m)$

#figure(image("media/Mod9_Verify.png"))
#figure(image("media/Mod11_Verify.png"))

*Multiplicative Inverse* $a x equiv 1 (mod m)$ has a solution $x in ZZ_m <==> gcd(a, m)=1$.
Also written $x equiv a^(-1) (mod m)$.

When given $u,v$ with $u a + v b = 1$, $a^(-1) (mod m) = R_m (u)$ because $a R_m (u) equiv a u equiv 1 - v m equiv 1$.

E.g., compute $142^(-1) (mod 553)$: Find $gcd(142, 553)$. We have $553 = 3*142 + 127$, then repeat until last step, substituting ($142 = 127 + 15$) until getting an expression $u a + v b = gcd(142, 553)$.

=== Chinese Remainder Theorem
Given pairwise relatively prime $m_1,..., m_r$, the system
$ x equiv a_1 (m_1) $
$ dots $
$ x equiv a_r (m_r) $
has a unique solution $0 <= x < product^r_(i=1) m_i$, where $0 <= a_i < m_i$ and $1 <= i <= r$.

*Application*
Compute $N = n_1 ... n_r$. For each congruence, define $N_i = N/n_i$.

Find an $M_i$ such that $N_i M_i equiv 1 (mod n_i)$.

Then sum, $x = sum^k_(i=1) a_i N_i M_i (mod N)$ *and reduce $mod N$*.

*Example*
Solving $x equiv 2 (mod 3), x equiv 3 (mod 5), x equiv 2 (mod 7)$:
- $N=3*5*7=105$
- $N_1 = 105/3 = 35, N_2 = 105/5=21, N_3 = 105/7=15$
- $35M_1 equiv 1 (mod 3) -> 2M_1 equiv 1 (mod 3) -> M_1 = 2$, etc.
- $x equiv 2*35*2 + ... -> x = 23+105k, k in ZZ$

#figure(image("media/CRT-Example.png"))


== DHKE
- Alice selects a random $x_A in {0, ..., p-2}$, Bob $x_B$
- Alice calculates $y_A = R_p (g^(x_A))$, Bob $y_B = R_p (g^(x_B))$
- They exchange $y_A, y_B$
- Alice calculates $k_(A B) = R_p (y_B^(x_A))$, Bob $k_(B A) = R_p (y_A^(x_B))$
Now, they have $k_(A B) equiv y_B^(x_A) equiv (g^(x_B))^(x_A) equiv g^(x_A x_B) equiv k_(B A)$

*Example*
Using $chevron.l 2 chevron.r in chevron.l ZZ^*_15; dot.o chevron.r$ ($g=2$). $y_A=8, k_(A B)=2$. Find $y_B$.

$
  8 = R_15 (2^(x_A)) ==> x_A = 3 ==> 2^(3 x_B) equiv_15 2 ==> 8^(x_B) equiv_15 2 ==> x_B=3 ==> y_B=R_15 (2^3)=8
$
