#import "@preview/lemmify:0.1.8": *
#let (
  theorem,
  lemma,
  corollary,
  remark,
  proposition,
  example,
  proof,
  rules: thm-rules,
) = default-theorems(
  "thm-group",
  lang: "en",
)
#let lemma = lemma.with(numbering: none)
#let theorem = theorem.with(numbering: none)
#show: thm-rules

*Operation* An operation on $S$ is a (partial) function $S^n -> S$ (if $n=1$, unary; if $n=2$, binary).

*Algebra* Written $chevron.l S; Omega chevron.r$, where $S$ is the carrier and $Omega=(omega_1, ... omega_n)$ is a list of operations.

Notation: Redundant operations and elements are sometimes dropped, e.g., $chevron.l ZZ; +, dot chevron.r$ instead of $chevron.l ZZ; +, -, 0, dot, 1 chevron.r$.

*Monoids* $chevron.l M; *, e chevron.r$ where $*$ is associative, $e$ neutral. Has one binary and up to one null-, unary operation. Examples being $+,*$ on $ZZ,QQ,RR$ and modular $+,*$ on $ZZ_m$.\

*Neutral Elements* Element $e in S$ such that $e*a=a$ (left) or $a*e=a$ (right). If there are two neutral elements, they are equal.

*Inverses* An $hat(a) in S$ such that $hat(a)*a=e$ (left) or $a*hat(a)=e$ (right). If there are two inverses, they are equal.

*Group* $chevron.l G; *, hat, e chevron.r$ satisfying the axioms G1, G2, G3:
1. $*$ is associative.
2. $e$ is a neutral element such that $forall a in G": " a*e=e*a=a$ (minimal version: $a*e=a$).
3. Every $a in G$ has an inverse $hat(a)$ such that $a*hat(a)=hat(a)*a=e$ (minimal version: $a* hat(a)=e$).
Examples being $chevron.l ZZ\/ZZ_m\/QQ\/RR; +, -, 0 chevron.r$, $chevron.l (QQ\/RR) backslash {0}; dot,^(-1), 1 chevron.r$. A group is called abelian (commutative) if $forall a,b in G": " a*b=b*a$

#lemma(name: "5.3")[$forall a,b,c in G$, $chevron.l G; *, hat, e chevron.r$:

  + $hat((hat(a)))=a$
  + $hat(a * b) = hat(b) * hat(a)$
  + $a*b = a*c ==> b=c$ (left) and $b*a=c*a ==> b=c$ (right)
  + $a*x=b$ and $x*a=b$ have a unique solution $x$ for any $a,b$.
]

*Subgroups* $chevron.l H; *, hat, e chevron.r$ is a subset of a group $chevron.l G; * hat, e chevron.r$ if:
- $forall a,b in H. a*b in H$
- $e in H$
- $forall a in H. hat(a) in H$
Every group has itself and ${e}$ as trivial subgroups.

*Number of subgroups:* $sum_(a | n and b | m) gcd(a, b)$ (non-script)

*Direct Product* The direct product of $n$ groups $chevron.l G_1; *_1 chevron.r, dots, chevron.l G_n; *_n chevron.r$ is the algebra $chevron.l G_1 times dots times G_n; star chevron.r$. The operation $star$ is applied component-wise, i.e., $ (a_1, dots a_n) star (b_1, dots b_n)= a_1*_1 b_1, dots $

The order of an $(a,b) in G times H$ is $lcm("ord"(a), "ord"(b))$. If the two orders are relatively prime, the order of $(a,b)$ is the product of their orders. If $G,H$ cyclic with relatively prime orders, $G times H$ cyclic.

$|G times H| = |G| |H|$

*Homo- and Isomorphisms* Given $chevron.l G; *, hat, e chevron.r, chevron.l H; star, tilde, e' chevron.r$, a function $phi: G -> H$ is a homomorphism if:
$ phi(a*b)=phi(a) star phi(b) $
A homomorphism must satisfy $phi(e)=e',phi(hat(a))=hat(phi(a))$ -- both *neutral elements and inverses are preserved*.

Example -- $log$ is a homomorphism from $chevron.l RR^(>0); dot chevron.r -> chevron.l RR; + chevron.r$ since $log(a dot b) = log(a)+log(b)$

#theorem(name: "5.7")[
  A cyclic group of order $n$ is isomorphic to $chevron.l ZZ_n; ⊕ chevron.r$ (and hence abelian).
]
$ZZ_(n m) tilde.equiv ZZ_n times ZZ_m$ if $gcd(n, m)=1$

*Euler's Totient and $ZZ^*_m$* $={a in ZZ_m : gcd(a, m) = 1}$; $phi(p^e)=(p-1)p^(e-1)$ for primes $p$.
$ phi(m)=|ZZ^*_m| = product^r_(i=1)(p_i-1)p_i^(e_i-1) = m product_(p|m,"prime"(p)) (1-1/p) $

$chevron.l ZZ^*_m; dot,^(-1), 1 chevron.r$ is a group.

*Explain why.*

$a^phi(m) equiv 1 (mod m)$ and hence $a^(p-1) equiv 1 (mod p)$ for primes $p$ (i.e., where $gcd(a, m)=1$). Also, $a^x (mod m) equiv a^(x mod phi(m)) (mod m)$ if $gcd(a, n)=1$.

== Order and Cyclic Groups
*Order*
- On Elements: The $m$ such that $a^m=e$. $"ord"(a)=infinity$ if there is no such $m$. If $"ord"(a)=2, a^(-1)=a$.
- On Groups: $|G|$ (and for every element, we have $a^(|G|)=e$)

*Cyclic Groups*
- $a^m=a^(R_("ord"(a))(m))$
- $chevron.l a chevron.r={a^n : n in ZZ}$ is the group generated by an $a in G$.

A group generated by an element $g in G$ is called cyclic. Cyclic groups of order $n$ are *commutative* and isomorphic to $chevron.l ZZ_n; + chevron.r$.

The order of a subgroup divides the group order. Thus, for a finite $G, forall g in G, "ord"(g)|"ord"(G)$, and $a^(|G|)=e$.

The number of generators is $phi(|G|)$ (non-script) and the set of generators is the coprime powers of an existing generator $g$: ${g^i : gcd(i, |G|)=1}$

*Every group of prime order is cyclic*, and every element except for $e$ is a generator. $chevron.l ZZ_p; + chevron.r$ is always cyclic. Groups $ZZ_a times ZZ_b$, are cyclic if $gcd(a, b)=1$.
== RSA
Define a group $G$ and find two large primes $p,q$.
- $n = p q$
- $|G| = |ZZ_n^*| = |ZZ_(p q)^*| = phi(n) = (p-1)(q-1)$

Then, let $e in ZZ$ be relatively prime to $|G|$ and $d equiv e^(-1) (mod |G|)$. Then, $x |-> x^e$ is a bijection and for all ciphertext messages $c=x^e$, $x = c^d = x^(e d)$.

Proof: $e d = k|G|+1$, so $x^(e d) = x^(k|G| + 1) = (x^(|G|))^k x = x$.

*Application*
- Select $e$ and find $d equiv e^(-1) (mod |G|)$
- Publish your $(n,e)$
- Other party calculates $c = R_n (m^e)$ and transmits it
- You calculate $m = R_n (c^d)$

== Rings, Fields
=== Rings
A ring $chevron.l R; +, -, 0, dot, 1 chevron.r$ is an algebra for which:
1. $chevron.l R; +, -, 0 chevron.r$ is a commutative group
2. $chevron.l R; dot, 1 chevron.r$ is a monoid
3. $a(b+c)=(a b)+(a c)$ and $(b+c)a=(b a)+(c a)$ (left, right distributivity)
A ring is called commutative if multiplication is commutative.

Additionally:
1. $0 a=a 0=0$
2. $(-a)b=-(a b)$
3. $(-a)(-b) = a b$
4. If $|R| > 1$, we have $1 eq.not 0$

*A finite field of order $q$ exists $<==> q$ is a prime power $p^k$.* $"GF"^*(q)$ has an order of $q-1$ with $phi(q-1)$ generators.

In a field of order $p^k$, the characteristic (number of times the mult. id needs to be added to get add. id) of the field is the prime base $p$, so $(x+y)^p=x^p+y^p$ holds (requires proof).

All fields of order $q$ are isomorphic.

A field cannot contain two different finite subfields with the same order (requires proof).

*Unit* $u$ is a unit if it is invertible such that $u v = v u = 1$. The units of $R$ are denoted $R^*$, which is itself a multiplicative group. 0 is never invertible in a mult. group.

For an integral domain $D$, the number of units in $D^* = D[x]^*$.

*Divisibility* $a|b <==> b = a c, c in R$.
In commutative rings, we have:
1. $a|b and b|c ==> a|c$
2. $a|b ==> a | b c$
3. $a|b and a|c ==> a | (b+c)$
Alternative definition of $gcd(a, b)=d$: $d|a ∧ d|b ∧ ∀c (c|a ∧ c|b) → c|d$

*Integral Domain* An element $a eq.not 0$ is a zerodivisor if $a b = 0$ for some $b eq.not 0$. An integral domain is a nontrivial commutative ring without zerodivisors.

*Polynomials Rings* Denoted $sum^d_(i=0) a_i x^i$. $deg(a(x))$ is the greatest $i$ for which $a_i eq.not 0$. $deg(0)=-infinity$.
- For a commutative ring $R$, $R[x]$ is also commutative.
- If $D$ is an integral domain, so is $D[x]$
  - The degree of the product of two polynomials is the sum of their degrees
  - The units of $D[x]$ are the constant polynomials that are units of $D$.
$RR[x]_(x^2+1) tilde.equiv CC$

=== Fields
A field is a commutative ring $F$ in which every nonzero element is a unit.
- $F "field" <==> chevron.l F backslash {0}; dot,^(-1), 1 chevron.r$ abelian group
- $ZZ_p "field" <==> "prime"(p)$ --- denoted $"GF"(p)$
Fields are integral domains. Multiplicative fields exclude 0.

=== Finite Fields
Example: $F[x]_m(x)$, i.e., if $m(x)$ is a polynomial of degree $d$, then $F[x]_m(x)={a(x) in F[x] : deg(a(x)) < d}$. Congruence modulo $m(x)$ is an equivalence relation on $F[x]$, and each equivalence class has a unique representative of degree less than $deg(m(x))$ (script).

If $|F| = q$ and $deg(m(x))=d$, then $|F[x]_m(x)| = q^d$.

$F[x]_m(x)$ is a ring under addition and multiplication $mod m(x)$.

Analogous to regular inverses, $a(x)b(x) equiv 1 (mod m(x))$ if they are inverses of each other and iff $gcd(a(x), m(x))=1$.

$F[x]_m(x)$ is a field iff $m(x)$ is irreducible.

== Polynomials
An $a(x) in F[x]$ is monic/normed if the leading coefficient is 1; irreducible if it is only divisible by constant polynomials and constant multiples of $a(x)$.

The monic $g(x)$ of largest degree such that $g(x) | a(x) and g(x)|b(x)$ is the $gcd(a(x), b(x))$.

Division with remainder: $a(x)=b(x)q(x)+r(x)$

*Evaluation* If $c(x) = a(x) + b(x)$, then $c(alpha)=a(alpha)+b(alpha)$ for any $alpha$. Same for multiplication.

*Roots* $alpha "root" <==> (x-alpha)|a(x)$

Polynomials of $deg$ 2 or 3 are irreducible $<==>$ they have no roots.

A nonzero polynomial $a(x)$ of degree $d$ has at most $d$ roots and is determined by any unique $d+1$ values of $a(x)$.

*$F[x]_m(x)$* Example: $5x^3-2x+1 equiv_(3x^2+2) 8x^3+1 equiv_(3x^2+2) -16/3 x + 1$

This structure is a ring under addition and multiplication $mod m(x)$.

=== Lagrange Interpolation
$ a(x) = sum^n_(i=0) y_i L_i(x) $
where $L_i(x)= product^n_(j=0,j eq.not i) (x-x_j)/(x_i-x_j)$.

e.g., given $(0,1), (1,3), (2,2)$, we have:
$ L_0(x)=((x-1)(x-2))/((0-1)(0-2)), L_1(x)=((x-0)(x-2))/((1-0)(1-2)), L_2(x)=((x-0)(x-1))/((2-0)(2-1)) $
$ ==> a(x) = 1dot L_0(x) + 3dot L_1(x) + 2dot L_2(x) $

== ECC
An $(n,k)$-encoding function $E$ over the alphabet $cal(A)$ is an injective function mapping a list $(a_0, ..., a_(k-1)) in cal(A)^k$ of $k$ symbols to a list $(c_0, ..., c_(n-1)) in cal(A)^n$ of $n>k$ encoded symbols in $cal(A)$ (a codeword).

Formally,
$
  E : cal(A)^k -> cal(A)^n : (a_0, ..., a_(k-1)) |-> E((a_0, ..., a_(k-1))) = (c_0, ..., c_(n-1))
$

Similarly, a decoding function $D: cal(A)^n -> cal(A)^k$.

The set of codewords $cal(C)=Im(E)$.

An $(n,k)$ error correcting code over an alphabet $cal(A)$ with $|cal(A)| = q$ is a subset of $cal(A)^n$ of cardinality $q^k$.

*Hamming Distance* The number of positions at which two strings differ.

*Minimum Distance* Minimum Hamming Distance.

*Error Correction Tolerance* A decoding function is $t$-error-correcting if for arbitrary $(a_0, ..., a_(k-1))$, the original message can be recovered. A *code* is $t$-error-correcting if there are $E,D$ with $C=Im(E)$ where $D$ is $t$-error-correcting.

A code with minimum distance $d$ is $t$-error-correcting iff $d >= 2t+1$.

*Polynomial Codes* If the code is over an $cal(A) = "GF"(q)$, one can use:
$
  E(( a_0, ..., a_(k-1) )) = ( a(alpha_0), ..., a(alpha_(n-1)) )
$
where $a(x)=a_(k-1)x^(k-1) + ... + a_1x + a_0$, giving a $d_min$ of $n-k+1$.
